# 文件: config.yaml

# Global settings for all sites
global_settings:
  timeout: 60
  max_retries: 3
  retry_delay: 5
  log_level: "DEBUG"
  request_delay: 0.5 # Default delay after actions like clicking 'new chat' (in seconds)
  concurrent_requests: 5
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
  idle_instance_check_interval_seconds: 60
  max_stale_instance_lifetime_seconds: 300

# API configurations
api_settings:
  openai:
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 2000
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
  anthropic:
    model: "claude-2"
    temperature: 0.7
    max_tokens: 2000

# Proxy settings
proxy_settings:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  bypass_list: []

# LLM sites configuration
llm_sites:
  - id: "wenxiaobai"
    name: "闻小AI (wenxiaobai.com)"
    enabled: true
    url: "https://www.wenxiaobai.com/"
    # 【修改】虽然我们用Chromium，但Profile目录名可以保持不变
    firefox_profile_dir: "profiles/wenxiaobai_profile" 
    playwright_launch_options:
      headless: false
      viewport:
        width: 1920
        height: 1080
      # --- 【核心修改】 ---
      # 添加启动参数来禁用后台节流
      args:
        - "--disable-background-timer-throttling"
        - "--disable-backgrounding-occluded-windows"
        - "--disable-renderer-backgrounding"
        - "--disable-hang-monitor"
    # --- 修改结束 ---
    use_stealth: true
    pool_size: 1
    max_requests_per_instance: 100
    max_memory_per_instance_mb: 1024

    selectors:
      new_chat_button: "xpath=//div[contains(@class, 'NewChat_left') and .//span[normalize-space()='新对话']]"
      input_area: "xpath=//textarea[@placeholder='给 小白 发送消息']"
      submit_button: "xpath=//div[@class='MsgInput_icon_container__4burH']//*[name()='svg']"
      response_markdown_body_last_assistant: "xpath=(//div[contains(@class, 'markdown-body') and @data-sentry-component='Markdown' and @data-sentry-source-file='index.tsx'])[1]"
      thinking_indicator: 'xpath=//*[@id="chat_turn_container"]//div[contains(@class, "loading-title") and normalize-space(.)="思考中..."]'
      model_selection_popup_trigger: "xpath=//div[contains(@class, 'PopupItem_btn_act__') and contains(@data-key, 'deepseek') and .//div[contains(@class, 'PopupItem_btn_msg__')]]"
      wenxiaobai_deepseek_v3_choice: "xpath=//div[contains(@class, 'PopupItem_option_item__') and .//div[contains(@class, 'PopupItem_option_text__') and text()='日常问答（V3）']]"
      wenxiaobai_deepseek_r1_choice: "xpath=//div[contains(@class, 'PopupItem_option_item__') and .//div[contains(@class, 'PopupItem_option_text__') and text()='深度思考（R1）']]"
      wenxiaobai_qwen3_choice: "xpath=//div[contains(@class, 'PopupItem_option_item__') and .//div[contains(@class, 'PopupItem_option_text__') and text()='千问 3']]"
      response_container_general: "xpath=(//div[contains(@class, 'Answser_answer_body_content')])[1]"
      last_response_options_trigger: "xpath=//*[@id='chat_turn_container']//div[starts-with(@class, 'TurnCard_right_opts') and contains(@class, 'TurnCard_more_opts_show')]"
      health_check_element: "xpath=//textarea[@placeholder='给 小白 发送消息']"

    model_variants:
      - id: "deepseek-v3"
        name_on_page: "日常问答（V3）"
        selection_flow:
          - selector_key: "model_selection_popup_trigger"
            description: "Click to open model selection popup"
            wait_after_ms: 500
          - selector_key: "wenxiaobai_deepseek_v3_choice"
            description: "Select DeepSeek V3 model"
            wait_after_ms: 200
      - id: "deepseek-r1"
        name_on_page: "深度思考（R1）"
        selection_flow:
          - selector_key: "model_selection_popup_trigger"
            wait_after_ms: 500
          - selector_key: "wenxiaobai_deepseek_r1_choice"
            wait_after_ms: 200
      - id: "qwen3"
        name_on_page: "千问 3"
        selection_flow:
          - selector_key: "model_selection_popup_trigger"
            wait_after_ms: 500
          - selector_key: "wenxiaobai_qwen3_choice"
            wait_after_ms: 200

    options_to_sync: []

    response_handling:
      type: "stream"
      stream_poll_interval_ms: 200
      stream_text_property: "textContent"
      extraction_selector_key: "response_markdown_body_last_assistant"
      extraction_method: "innerText"

      stream_end_conditions:
        - type: "element_disappears"
          selector_key: "thinking_indicator"
          priority: 0
        - type: "text_stabilized"
          stabilization_time_ms: 2500
          priority: 1
        - type: "timeout"
          timeout_seconds: 180
          priority: 2

      full_text_wait_strategy:
        - type: "element_disappears"
          selector_key: "thinking_indicator"
        - type: "element_contains_text_or_is_not_empty"
          selector_key: "response_markdown_body_last_assistant"

    health_check:
      enabled: true
      interval_seconds: 300
      timeout_seconds: 60
      failure_threshold: 3
      check_element_selector_key: "health_check_element"