# Global settings for all sites
global_settings:
  timeout: 30  # Default timeout in seconds
  max_retries: 3  # Default number of retries
  retry_delay: 5  # Delay between retries in seconds
  log_level: "INFO"
  request_delay: 1.0  # Delay between requests in seconds
  concurrent_requests: 5  # Maximum number of concurrent requests
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# API configurations
api_settings:
  openai:
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 2000
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
  anthropic:
    model: "claude-2"
    temperature: 0.7
    max_tokens: 2000

# Proxy settings
proxy_settings:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  bypass_list: []

# LLM sites configuration
llm_sites:
  - id: "local-chatgpt-clone"
    name: "Local ChatGPT Clone Interface"
    enabled: true
    url: "http://localhost:3000/chat"

    # Firefox Profile 配置
    firefox_profile_dir: "local_chatgpt_clone_profile"

    # Playwright 浏览器启动选项
    playwright_launch_options:
      headless: false  # 调试时设为 false，便于观察
      viewport:
        width: 1920
        height: 1080
    use_stealth: true

    # 浏览器实例池大小
    pool_size: 1  # 测试时使用单个实例

    # 实例资源限制
    max_requests_per_instance: 150
    max_memory_per_instance_mb: 1536

    # CSS 选择器
    selectors:
      input_area: "textarea#prompt-textarea"
      submit_button: "button[data-testid='send-message-button']"
      response_container: "div.chat-messages-container"
      last_response_message: "div.chat-messages-container > div.message-bubble[data-role='assistant']:last-child"
      streaming_response_target: "div.chat-messages-container > div.message-bubble[data-role='assistant']:last-child > div.content"
      thinking_indicator: "div.spinner-overlay.active"
      model_selector_dropdown: "select#model-selector"
      theme_toggle_dark: "button#theme-toggle[aria-label='Switch to dark theme']"

    # 备用选择器
    backup_selectors:
      input_area:
        - "textarea[name='user_prompt']"
        - "div.input-wrapper > textarea"
      submit_button:
        - "button.submit-chat"
        - "button[type='submit']"

    # 页面选项同步配置
    options_to_sync:
      - id: "model_selection_on_page"
        description: "Ensure the correct model is selected on the page"
        selector_key: "model_selector_dropdown"
        action: "select_by_value"
        target_value_on_page: "gpt-3.5-turbo"
        on_failure: "warn_and_skip"

      - id: "dark_theme_activation"
        description: "Ensure dark theme is active"
        selector_key: "theme_toggle_dark"
        action: "click_if_not_active"
        on_failure: "warn_and_skip"

    # 响应处理配置
    response_handling:
      type: "stream"
      stream_poll_interval_ms: 150
      stream_text_property: "textContent"
      stream_buffer_size: 1024  # 流式响应缓冲区大小(字节)
      stream_timeout_ms: 30000  # 流式响应超时时间(毫秒)
      stream_error_handling:
        max_retries: 2  # 流式响应错误重试次数
        retry_delay_ms: 500  # 重试间隔(毫秒)
        fallback_to_full_response: true  # 流式失败时是否回退到完整响应
      
      # 流式响应结束条件
      stream_end_conditions:
        - type: "element_disappears"
          selector_key: "thinking_indicator"
          priority: 0
        - type: "text_stabilized"
          stabilization_time_ms: 2500
          priority: 1
        - type: "timeout"
          timeout_seconds: 180
          priority: 2

      # 完整文本等待策略
      full_text_wait_strategy:
        - type: "element_disappears"
          selector_key: "thinking_indicator"
        - type: "element_contains_text_or_is_not_empty"
          selector_key: "last_response_message"
      
      extraction_selector_key: "last_response_message"
      extraction_method: "innerText"

    # 站点健康检查配置
    health_check:
      enabled: true
      interval_seconds: 300
      timeout_seconds: 45
      failure_threshold: 3
      check_element_selector_key: "input_area"