# 文件: models.py

from enum import Enum
from typing import Dict, List, Optional, Union, Any
from pydantic import BaseModel, Field, field_validator, model_validator

# --- Enums (无变化) ---
class LogLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

# --- 辅助模型，用于定义OpenAI兼容的字段 ---
class ResponseFormat(BaseModel):
    type: str = Field(..., description="Must be one of 'text' or 'json_object'.")

class FunctionDefinition(BaseModel):
    name: str = Field(..., description="The name of the function to be called.")
    description: Optional[str] = Field(default=None, description="A description of what the function does.")
    parameters: Dict[str, Any] = Field(..., description="The parameters the functions accepts, described as a JSON Schema object.")

class Tool(BaseModel):
    type: str = Field(..., description="The type of the tool. Currently, only 'function' is supported.")
    function: FunctionDefinition

class ToolChoiceFunction(BaseModel):
    name: str

class ToolChoice(BaseModel):
    type: str
    function: ToolChoiceFunction

# --- 核心修改在此：OpenAIMessage 模型 ---
class OpenAIMessage(BaseModel):
    """
    一个与OpenAI API高度兼容的消息对象。
    它能接受多种格式的 content，并在验证阶段将其统一转换为字符串，
    以便后端自动化逻辑能以统一的方式处理。
    """
    # 允许 content 是字符串或一个复杂的列表（例如包含图片URL或多个文本块）
    content: Union[str, List[Dict[str, Any]]] = Field(..., description="The content of the message.")
    role: str = Field(..., description="The role of the message author.")
    
    # 兼容工具调用所需的字段
    name: Optional[str] = Field(default=None, description="The name of the author of this message.")
    tool_calls: Optional[List[Dict]] = Field(default=None, description="The tool calls generated by the model, if any.")
    tool_call_id: Optional[str] = Field(default=None, description="Tool call that this message is responding to.")

    @field_validator('role')
    @classmethod
    def validate_role(cls, v: str) -> str:
        # 添加 'tool' 角色以提高兼容性
        allowed_roles = ['system', 'user', 'assistant', 'function', 'tool']
        if v not in allowed_roles:
            raise ValueError(f"Role must be one of {allowed_roles}")
        return v
    
    # --- 这是实现您需求的核心：一个健壮的预处理验证器 ---
    @model_validator(mode='before')
    @classmethod
    def transform_complex_content_to_string(cls, data: Any) -> Any:
        """
        在Pydantic模型验证之前，预处理传入的数据。
        主要目标：将各种形式的 'content' 字段统一转换为一个字符串。
        """
        if not isinstance(data, dict):
            return data # 如果不是字典，直接返回

        content = data.get('content')
        if content is None:
            # 如果没有content，pydantic的后续验证会处理，这里设为空字符串以防意外
            data['content'] = "" 
            return data

        if isinstance(content, str):
            # 如果已经是字符串，无需处理
            return data

        # 如果 content 是一个列表 (最常见的复杂情况)
        if isinstance(content, list):
            full_text_parts = []
            for part in content:
                if not isinstance(part, dict):
                    # 如果列表里有非字典项，强转为字符串
                    full_text_parts.append(str(part))
                    continue

                part_type = part.get('type')
                if part_type == 'text':
                    # 提取文本部分
                    full_text_parts.append(part.get('text', ''))
                elif part_type == 'image_url':
                    # 对于图片，我们可以选择忽略，或提取URL，或用占位符表示
                    # 这里我们选择用一个占位符来告知LLM这里有张图片
                    # 您的浏览器自动化后端可能无法处理图片，但这样可以让LLM知道上下文
                    image_url_obj = part.get('image_url', {})
                    if isinstance(image_url_obj, dict):
                         url = image_url_obj.get('url', '[Image URL not found]')
                         full_text_parts.append(f"[User provided an image: {url.split('?')[0]}]") # 只显示URL主干
                    else:
                         full_text_parts.append(f"[User provided an image: {str(image_url_obj)}]")
                else:
                    # 对于其他未知的字典类型，尝试提取text字段，否则转为字符串
                    full_text_parts.append(part.get('text', str(part)))
            
            # 将所有部分用换行符拼接成一个单一的字符串
            data['content'] = "\n\n".join(filter(None, full_text_parts))
            return data

        # 如果 content 是其他类型（非字符串、非列表），则安全地转换为字符串
        data['content'] = str(content)
        return data


class OpenAIChatCompletionRequest(BaseModel):
    """
    定义了与OpenAI v1/chat/completions端点高度兼容的请求体。
    所有非核心功能（如tools, logprobs等）都是可选的，后端可以安全地忽略它们。
    """
    model: str
    messages: List[OpenAIMessage]
    
    # 标准参数
    temperature: Optional[float] = Field(default=0.7, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(default=1.0, ge=0.0, le=1.0)
    n: Optional[int] = Field(default=1, description="How many chat completion choices to generate for each input message.")
    stream: Optional[bool] = Field(default=False)
    stop: Optional[Union[str, List[str]]] = Field(default=None)
    max_tokens: Optional[int] = Field(default=None, description="The maximum number of tokens to generate in the chat completion.")
    presence_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    frequency_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    logit_bias: Optional[Dict[str, float]] = Field(default=None)
    user: Optional[str] = Field(default=None, description="A unique identifier representing your end-user.")
    
    # 新增的兼容性参数 (后端可忽略)
    logprobs: Optional[bool] = Field(default=False, description="Whether to return log probabilities of the output tokens.")
    top_logprobs: Optional[int] = Field(default=None, ge=0, le=20, description="An integer between 0 and 20 specifying the number of most likely tokens to return at each token position.")
    response_format: Optional[ResponseFormat] = Field(default=None, description="An object specifying the format that the model must output.")
    seed: Optional[int] = Field(default=None, description="A seed for deterministic sampling.")
    tools: Optional[List[Tool]] = Field(default=None, description="A list of tools the model may call.")
    tool_choice: Optional[Union[str, ToolChoice]] = Field(default=None, description="Controls which tool the model should use.")

    # 兼容旧版的函数调用 (后端可忽略)
    functions: Optional[List[Dict]] = Field(default=None, description="Deprecated in favor of 'tools'.")
    function_call: Optional[Union[str, Dict]] = Field(default=None, description="Deprecated in favor of 'tool_choice'.")

# --- 响应模型 (结构保持不变) ---
class OpenAIFunctionCall(BaseModel):
    name: str
    arguments: str

class OpenAIChatChoice(BaseModel):
    index: int
    message: OpenAIMessage
    finish_reason: str
    function_call: Optional[OpenAIFunctionCall] = None

class OpenAIUsage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int

class OpenAIChatStreamDelta(BaseModel):
    role: Optional[str] = None
    content: Optional[str] = None

class OpenAIChatStreamChoice(BaseModel):
    index: int
    delta: OpenAIChatStreamDelta
    finish_reason: Optional[str] = None

class ChatCompletionStreamResponse(BaseModel):
    id: str
    object: str = "chat.completion.chunk"
    created: int
    model: str
    choices: List[OpenAIChatStreamChoice]

class OpenAIChatCompletionResponse(BaseModel):
    id: str
    object: str
    created: int
    model: str
    choices: List[OpenAIChatChoice]
    usage: OpenAIUsage

# --- 其余配置模型 (无变化) ---
class ViewportConfig(BaseModel):
    width: int = 1920
    height: int = 1080

class PlaywrightLaunchOptions(BaseModel):
    headless: bool = True
    viewport: Optional[ViewportConfig] = None
    user_agent: Optional[str] = None
    slow_mo: Optional[int] = None
    channel: Optional[str] = Field(default=None)
    args: Optional[List[str]] = Field(default=None)


class StreamEndCondition(BaseModel):
    type: str
    selector_key: Optional[str] = None
    stabilization_time_ms: Optional[int] = None
    timeout_seconds: Optional[int] = None
    priority: int = 999

class WaitStrategy(BaseModel):
    type: str
    selector_key: Optional[str] = None
    attribute_name: Optional[str] = None
    attribute_value: Optional[str] = None

class ResponseHandling(BaseModel):
    type: str
    stream_poll_interval_ms: int = 150
    stream_text_property: str = "textContent"
    stream_end_conditions: List[StreamEndCondition] = Field(default_factory=list)
    full_text_wait_strategy: List[WaitStrategy] = Field(default_factory=list)
    extraction_selector_key: str
    extraction_method: str = "innerText"
    stream_error_handling: Optional[Dict[str, Any]] = None
    extraction_selector_key_relative_to_assistant_item: Optional[str] = None

class OptionSync(BaseModel):
    id: str
    description: str
    selector_key: str
    action: str
    target_value_on_page: Optional[str] = None
    on_failure: str = "abort"

class HealthCheck(BaseModel):
    enabled: bool = True
    interval_seconds: int = 300
    timeout_seconds: int = 45
    failure_threshold: int = 3
    check_element_selector_key: str

class ModelSelectionStep(BaseModel):
    action: str = Field(default="click", description="Action to perform, e.g., 'click'")
    selector_key: str = Field(..., description="Key from the main 'selectors' dict for the target element")
    description: Optional[str] = None
    wait_after_ms: Optional[int] = Field(default=None, description="Optional delay in milliseconds after this action")

class ModelVariantConfig(BaseModel):
    id: str = Field(..., description="Unique ID for this model variant, used in API requests (e.g., 'deepseek-v3'). This is the part after site_id/")
    name_on_page: Optional[str] = Field(default=None, description="Human-readable name as it appears on the page, for logging/reference.")
    selection_flow: List[ModelSelectionStep] = Field(..., description="Sequence of actions to select this model variant.")

class LLMSiteConfig(BaseModel):
    id: str
    name: str
    enabled: bool = True
    url: str
    firefox_profile_dir: str
    playwright_launch_options: PlaywrightLaunchOptions = Field(default_factory=PlaywrightLaunchOptions)
    use_stealth: bool = True
    pool_size: int = Field(default=1, ge=1, description="Number of browser instances for this site's pool.")
    max_requests_per_instance: int = 100
    max_memory_per_instance_mb: int = 1024
    selectors: Dict[str, str]
    backup_selectors: Optional[Dict[str, List[str]]] = None
    options_to_sync: List[OptionSync] = Field(default_factory=list)
    model_variants: Optional[List[ModelVariantConfig]] = Field(default=None, description="Configuration for different model variants on this site and how to select them.")
    response_handling: ResponseHandling
    health_check: HealthCheck
    mock_mode: bool = False
    mock_responses: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Mock responses for testing purposes"
    )

class GlobalSettings(BaseModel):
    timeout: int = 30
    max_retries: int = 3
    retry_delay: int = 5
    log_level: LogLevel = LogLevel.INFO
    request_delay: float = 1.0
    concurrent_requests: int = 5
    user_agent: str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    idle_instance_check_interval_seconds: int = Field(default=60, description="Interval for checking idle browser instances in pools.")
    max_stale_instance_lifetime_seconds: int = Field(default=300, description="Max lifetime for instances marked stale after config reload (seconds).")

class APISettings(BaseModel):
    model: str
    temperature: float = 0.7
    max_tokens: int = 2000
    top_p: float = 1.0
    frequency_penalty: float = 0.0
    presence_penalty: float = 0.0

class APIConfigurations(BaseModel):
    openai: APISettings
    anthropic: Optional[APISettings] = None
    
class ProxySettings(BaseModel):
    enabled: bool = False
    http_proxy: Optional[str] = None
    https_proxy: Optional[str] = None
    bypass_list: List[str] = Field(default_factory=list)

class AppConfig(BaseModel):
    global_settings: GlobalSettings
    api_settings: APIConfigurations
    proxy_settings: ProxySettings = Field(default_factory=ProxySettings)
    llm_sites: List[LLMSiteConfig] = Field(default_factory=list)

# --- API 别名，确保完整性 ---
ChatCompletionRequest = OpenAIChatCompletionRequest
ChatCompletionResponse = OpenAIChatCompletionResponse